version: '3.9'
services:
  plexripper:
    container_name: PlexRipper
    image: plexripper/plexripper:dev
    environment:
      - PUID=1000
      - PGID=1000
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      # Web UI & Web API
      - '7000:7000'
    volumes:
      - /mnt/PROJECTS/PlexRipperE2ETesting/Config:/Config
      - /mnt/PROJECTS/PlexRipperE2ETesting/Downloads:/Downloads
      - /mnt/PROJECTS/PlexRipperE2ETesting/Movies:/Movies
      - /mnt/PROJECTS/PlexRipperE2ETesting/TvShows:/TvShows

  cypress-e2e:
    container_name: PlexRipperCypress
    image: cypress/plexripper
    build:
      context: .
      dockerfile: ./cypress.dockerfile
    depends_on:
      - plexripper
    environment:
      - CYPRESS_baseUrl=http://plexripper:7000
    command: npx cypress run
