version: '3.9'
services:
  plexripper:
    container_name: PlexRipper
    image: plexripper/plexripper:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - PUID=1000
      - PGID=1000
    build:
      context: .
      dockerfile: ./Dockerfile
    # restart: always
    ports:
      # Web UI & Web API
      - '5000:5000'
    volumes:
      - /mnt/PROJECTS/PlexRipperCache/Config:/config
      - /mnt/PROJECTS/PlexRipperCache/Downloads:/downloads
      - /mnt/PROJECTS/PlexRipperCache/Movies:/movies
      - /mnt/PROJECTS/PlexRipperCache/TvShows:/tvshows



