version: '3.9'
services:
  plexripper:
    container_name: PlexRipper
    image: plexripper/plexripper:dev
    environment:
      - PUID=1000
      - PGID=1000
    build:
      context: .
      dockerfile: ./Dockerfile
    # restart: always
    ports:
      # Web UI & Web API
      - '7000:7000'
    volumes:
      - /mnt/PROJECTS/PlexRipperCache/Config:/Config
      - /mnt/PROJECTS/PlexRipperCache/Downloads:/Downloads
      - /mnt/PROJECTS/PlexRipperCache/Movies:/Movies
      - /mnt/PROJECTS/PlexRipperCache/TvShows:/TvShows



