name: Create PlexRipper Dev Container Release

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.run/**'
      - '.vscode/**'
jobs:
  SemanticRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm --prefix src/WebAPI/ClientApp/ install
      - name: GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ env.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ env.GIT_COMMITTER_EMAIL }}
        run: npx --prefix src/WebAPI/ClientApp/ semantic-release
  # Build Docker Image
  CreateDockerDevRelease:
    needs: [ SemanticRelease ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Publish to Registry with dev tag
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
        with:
          name: plexripper/plexripper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: VERSION
          tags: "dev"
