name: Create PlexRipper Dev Container Release

on:
  push:
    tags:
      - "*"

jobs:
  # Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker with version tag
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: plexripper/plexripper
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          tag_names: true
      - name: Publish to Registry with dev tag
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: plexripper/plexripper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "dev"
