name: Execute Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.run/**'
      - '.vscode/**'
jobs:
  Back-End-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          cache: true
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore dependencies
        run: dotnet restore PlexRipper.sln
      - name: Build
        run: dotnet build PlexRipper.sln --no-restore
      - name: Unit Tests
        run: dotnet test tests/UnitTests/UnitTests.sln --no-build --verbosity normal
  Back-End-Integration-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          cache: true
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore dependencies
        run: dotnet restore PlexRipper.sln
      - name: Build
        run: dotnet build PlexRipper.sln --no-restore
      - name: Integration Tests
        run: dotnet test tests/IntegrationTests/IntegrationTests.sln --no-build --verbosity normal
  Front-End-Unit-Tests:
    defaults:
      run:
        working-directory: src/WebAPI/ClientApp/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v18.11
        uses: actions/setup-node@v3
        with:
          node-version: 18.11
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Clean install npm modules
        run: npm ci
      - name: Build front-end
        run: npm run build --if-present
      - name: Run Vitest tests
        run: npm test
  Test-Docker-Build:
    needs: [ Front-End-Unit-Tests, Back-End-Unit-Tests, Back-End-Integration-Tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry with dev tag
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: plexripper/plexripper
          no_push: true
