name: Execute Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      [master, dev]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore PlexRipper.sln
    - name: Build
      run: dotnet build PlexRipper.sln --no-restore
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.sln --no-build --verbosity normal
    - name: Setup Node@v3  
      uses: actions/setup-node@v3
    - name: Install npm modules
      run: npm ci
    - name: Build front-end
      run: npm run build --if-present
    - name: Run Jest tests
      run: npm test